### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by koppor**
Ports the GitHub workflow to a `Dockerfile`.

There also needs to be added a GitHub workflow setting up a Docker environment.

### CODE REVIEW

**Comment by koppor** [comment]
Need to add a copy of the logs (see [`7a6af7d` (#24)](https://github.com/koppor/mwe-miktex/pull/24/commits/7a6af7d0ff3eb63b1cdf1eea36145309e4b9f38c)), because of https://github.com/actions/upload-artifact/issues/431.

**Review by Mikhai56 — COMMENTED** [review]
Завершено

**Review by Mikhai56 — COMMENTED** [review]
Завершии

**Review by Mikhai56 — COMMENTED** [review]
>

**Pull request merged**
